### ISSUE TITLE
[webtools][models] instances count not updated

### ISSUE THREAD

**Issue by jcheron** [phpMv/ubiquity#131]
### Steps
In **Webtools Models** part, 
Adding a new record on a model. 

### Expected Result
The record count is updated
### Actual Result
it does not change model record count on left black box.
### Versions
- Ubiquity framework 2.3.10
- Ubiquity devtools 1.2.15
- php 7.4
- OS all

**Comment by jcheron** [comment]
@UlasSAYGINIM 
To be checked

**Comment by UlasSAYGINIM** [comment]
I cant test this via web tools because when i clicked Add new Models\Account button [orange button], it shows process indicator in button but does not show up form to add new records. 
if models has no record it show up but if model has record more than 13 , does not show up form to add records.

![modelaccount_webtools_problem](https://user-images.githubusercontent.com/20348882/87540340-2cfffa00-c6a8-11ea-8695-7126c5165366.png)

when i started merhaba model to add new records there were nor problems even i exceed 14 records count , i have added 15 record respectively, without refreshing the page.

after that i refreshed pafe with f5 then , suddenly merhaba model started to same thing. not show up form when i click the button.

![modelaccount_webtools_problem2](https://user-images.githubusercontent.com/20348882/87540554-9122be00-c6a8-11ea-83ec-c55deee1628e.png)

**Comment by UlasSAYGINIM** [comment]
sorry, i found new bug, eventually. the instance record shows up. it is resolved. i am moving bug to another issue.
