### ISSUE TITLE
[bug] protected header/footer breaks custom html

### ISSUE THREAD

**Issue by a1git** [phpMv/ubiquity#180]
### Steps

created a test controller  called "test.php"
created a html file 

### Expected Result
the file should load with the css/js from html

### Actual Result

the css/js is broken due to 
	protected $headerView = "@activeTheme/main/vHeader.html";
	protected $footerView = "@activeTheme/main/vFooter.html";

being passed 

### Versions
   · PHP 7.4.16
    · Ubiquity devtools (1.2.28)
    · Ubiquity webtools (2.4.8)
    · Ubiquity 2.4.4
    · OS: Linux sd 5.11.0-16-generic #17-Ubuntu SMP Wed Apr 14 20:12:43 UTC 2021 x86_64

**Comment by jcheron** [comment]
If the controller is created with devtools:
```bash
Ubiquity controller test
```

The controller code will be as follows:
```php
<?php
namespace controllers;

 /**
  * Controller Test
  */
class Test extends ControllerBase{
	public function index(){}

}
```

I don't see which css/js are not loaded

**Comment by a1git** [comment]
./vendor/bin/Ubiquity controller atl -v                                                                                                           ─╯

    · The project folder is /project/web/stats
     ╭───────────────────────────────────────────────────────────────────────────────────────────────────────╮
     │      ■ success : Controller creation                                                                  │
     │      · Creation of the Controller Atl at the location app/controllers/Atl.php                         │
     │      · Creation of the the associated view index.html at the location app/views/Atl/index.html        │
     ╰───────────────────────────────────────────────────────────────────────────────────────────────────────╯


Then i have to ironically do  http://localhost:8090/Atl  [ and not small atl like very other PHP framework .. why ? ]
so I have to now go and edit app/controllers/Atl.php and add this line to make it look like:

<?php
namespace controllers;

 /**
 * Controller Atl
 * @route("/atl","automated"=>true)
 **/
class Atl extends ControllerBase{
        #[Route('atl')]
	public function index(){
		$this->loadDefaultView();
	}

}



Ubiquity init-cache
 ■ success : init-cache:all



http://localhost:8090/Atl  -- still works 
http://localhost:8090/atl -- also works .. 

-- why are both working? if I manually change the route to /atl ( all small) , i don't want  /Atl to exist or even work .. so how to disable this ? 


http://localhost:8090/atl
this by default, the view gives me a blank page with   some green/orange background page -- and nothing else

Now I edit 
app/views/Atl/index.html  

<html>
<head>
<title>Test Page</title>
</head>
<body>
 ABC
</body>
</html>



I refresh 

I get the ABC body, and the title is there, but I still get the   green/orange background page.
when I view source, I get this:

<!DOCTYPE html>
<html>
<head>
	<base href="http://127.0.0.1:8090/">
	<meta charset="UTF-8">
	<link rel="icon" href="data:;base64,iVBORw0KGgo=">
	<title>stats</title>
	<link href="https://cdn.jsdelivr.net/npm/fomantic-ui@2.8.7/dist/semantic.min.css" type="text/css" rel="stylesheet" >
	<link href="public/assets/css/style.css" type="text/css" rel="stylesheet" >
</head>
<body>
<html>
<head>
<title>Test Page</title>
</head>
<body>
 ABC
</body>
</html>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" ></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/fomantic-ui@2.8.7/dist/semantic.min.js" ></script>
</body>
</html>



But I only want the page I have above to be rendered. Why is it adding all these stuff ?

**Comment by jcheron** [comment]
### About the routes

2 routing systems exist:
### Default routing
Controller, method (action) and action parameters define URLs.
in the form `controllerName/methodName/parameters`

The `Atl` controller and its index method define the following Urls:
- `/Atl`
- `/Atl/index`

### Attributes/annotations routing
Routing by annotations (php7) or by attributes completes this system:

With php8 attributes:
```php
        #[Route('atl')]
	public function index(){
		$this->loadDefaultView();
	}
```
With the old annotations system
```php
        /**
         * @route('alt')
         * /
	public function index(){
		$this->loadDefaultView();
	}
```

One or the other adds an additional route:
- `/alt` with lowercase first letter

But the default routing is still active, so you now have 3 urls:

- `/Atl`
- `/Atl/index`
- `/atl`

If you want to disable the default routing, you need to add an additional route:
```php
	#[Route('{url}', priority: -1000)]
	public function p404($url){
		echo "<div>The page `$url` you are looking for doesn't exist!</div>";
	}
```
Or you can simply disable access to the default routes for this controller:
```php
	#[Route('/Atl/{url}', priority: -1000)]
	public function notAtl($url=''){
		echo "<div>The page `/Atl/$url` you are looking for doesn't exist!</div>";
	}
```
It is often preferable to use attribute/annotation routing, and to disable default routing.
To avoid:
- exposing the application logic (controller and method names)
- unintentionally giving access to an exposed controller method 
and to better control the chosen urls

###Views
A controller automatically created with devtools or webtools inherits from the BaseController class:
```php
class Home extends ControllerBase{}
```
This `ControllerBase` class loads the header and footer views in the methods `initialize` and `finalize`, automatically called before and after each action
```php
abstract class ControllerBase extends Controller {

	protected $headerView = "@activeTheme/main/vHeader.html";

	protected $footerView = "@activeTheme/main/vFooter.html";

	public function initialize() {
		if (! URequest::isAjax()) {
			$this->loadView($this->headerView);
		}
	}

	public function finalize() {
		if (! URequest::isAjax()) {
			$this->loadView($this->footerView);
		}
	}
}
```
If you don't want this behaviour, and do not want to load these views, you can:

Either make your controller inherit from the Controller class:
```php
namespace controllers;
 use Ubiquity\controllers\Controller;

class Atl extends Controller {
	public function index(){
		$this->loadDefaultView();
	}
}
```
Override the `initialize` and/or `finalize` methods in your controller, so that you can do what you want:

```php
<?php
namespace controllers;

class Atl extends ControllerBase{
	public function initialize() {
            //Override
	}

	public function index(){
		$this->loadDefaultView();
	}

}
```

**Comment by a1git** [comment]
"It is often preferable to use attribute/annotation routing, and to disable default routing."
I agree completely, so why cannot this be a feature request, so that the framework itself disables default routing if annotations/attributes is present. 

because otherwise, if say my application has 200+ different routes/pages, you are forcing me to add the example lines 500 times. 
--------
#[Route('/Atl/{url}', priority: -1000)]
	public function notAtl($url=''){
		echo "<div>The page `/Atl/$url` you are looking for doesn't exist!</div>";
	}
--------

because coming from symfony/codeigniter and other frameworks, I don't think we need 3 different routes possibility.. Most people and in reality, we expect if controller is ABC, it can be called as  /abc and method all in small caps.. so I think this can be made a feature request for the framework to handle itself, and not force the user to override the default route on every function. 

In the example above,  if the controller I add is called Atl / or ATL  or ATl etc, 
its good to get: 
    /atl
    /atl/index
    
    and if I want something else, i can just add a attribute/annotation to make it ATl, hello etc .. 
I don't see a valid reason or any user expectation of using Caps format

**Comment by jcheron** [comment]
Whatever the number of controllers and routes, you can disable default routing by adding this statement once in any of the controllers:
```php
	#[Route('{url}', priority: -1000)]
	public function p404($url){
		echo "<div>The page `$url` you are looking for doesn't exist!</div>";
	}
```
Disabling default routing from the moment a route is declared would be possible, but I don't see the point.
It's better to let the developer choose.

With the default routing system, the routes created match `controllerName/actionName` pattern exactly, case sensitive.
This simple logic limits the amount of checking that needs to be done on the existence of the controller and the corresponding action.
Again, the developer has the option of removing this constraint by explicitly declaring a route in the controller:

```php
<?php
namespace controllers;

 use Ubiquity\attributes\items\router\Route;
 use Ubiquity\controllers\Controller;

#[Route("/atl",automated: true)]
 class Atl extends Controller {
	public function index(){
		echo "/home";
	}

	public function test(){
		echo "/test";
	}
     
}
```
The `automated` attribute on the declared route ensures that all routes associated with the controller's public methods are automatically generated.

In the above case, the following routes are created, and are case insensitive:
- /atl
- /atl/index
- /atl/test

But automated is an expedient relief that exposes the same risks as default routing:
you can unintentionally create routes to methods that should not have been exposed.

The most recommended method of not having to worry about urls and their case is to systematically declare the routes and fill in their name property.
You can then simply use the route name (rather than its url) to refer to it.

```php
<?php
namespace controllers;

 use Ubiquity\attributes\items\router\Route;
 use Ubiquity\controllers\Controller;

#[Route("/atl")]
 class Atl extends Controller {
	#[Route(name: 'atl.index')]
	public function index(){
		echo "/home";
	}

	#[Route(name: 'atl.test')]
	public function test(){
		echo "/test";
	}
     
}
```

You can then refer to a route by its name,
to generate an url in a template:
```html
<a href="{{ path('atl.index') }}">Atl index</a>
<a href="{{ path('atl.test') }}">Atl test</a>
```
In this case, it does not matter whether the url contains capital letters or not...
And this method allows you to change your urls, without refactoring the code.

**Comment by LX-3** [comment]
@a1git I'm not sure I'm right but I think there is a workaround, I personally use in _**app/config/services.php**_ :

```php
Router::addRoute("_default", controllers\DefaultController::class, 'index');
Router::addRoute("(A|a)dmin.*", controllers\DefaultController::class, 'r404');
```

to disable web view and redirect default queries to a predefined index/welcome method. Also I keep an empty index method in implemanted version of my controllers (for framework legacy support..) and I think I cannot put it in the abstract  ControllerBase... 

Also you can redirect NOT FOUND errors using _**app/config/config.php**_ like this :

```php
    "sessionName" => null, // sessionName set to null to disable cookies
    "onError" => function ($code, $message = null, $controller = null) {
        switch ($code) {
            case 404:
                $init = ($controller == null);
                \Ubiquity\controllers\Startup::forward('DefaultController/r404', $init, $init); // api error
                //\Ubiquity\controllers\Startup::forward('IndexController/p404', $init, $init); // page error
                break;
        }
    },
```

Hope this can help, regards.
LX

**Comment by jcheron** [comment]
@LX-3 Just a micro-optimization:
It is better to use annotations/attributes to define routes, rather than explicitly calling the addRoute method.
This saves the processing of adding the route, and takes advantage of caching.

```php

class DefaultController extends ControllerBase{
	#[Route('_default',name: 'home')]
	public function index(){...}
}
```

Concerning the index method, you can indeed define it in the `ControllerBase`class, so that you don't have to do it in all the derived classes.
