### ISSUE TITLE
New project template using DevTools has invalid link to Admin page

### ISSUE THREAD

**Issue by ekscrypto** [phpMv/ubiquity#8]
### Steps
$ Ubiquity new ubiquityProject -a -q=semantic
$ cd ubiquityProject
$ Ubiquity serve
...
· Starting php server at 127.0.0.1:8090...

Using a browser open http://127.0.0.1:8090

### Expected Result
In the footer of the page, there should be a link "UbiquityMyAdmin" link that points to: http://127.0.0.1:8090/Admin

### Actual Result
In the footer of the page, there is a "UbiquityMyAdmin" link that points to: http://127.0.0.1/ubiquityProject/Admin

### Versions
- Ubiquity framework dev-master (2019-02-26)
- Ubiquity devtools 1.1.5
- php 7.3.2

**Comment by jcheron** [comment]
Thank you for reporting,
It will be better with access to the admin!

Fixed in https://github.com/phpMv/ubiquity-devtools/commit/d1174e8f08d46f6ed7048831325c38617426786c, for the next installations.

For an already existing project,
you have to modify the file `.ubiquity/.htrouter.php`  this way:

```php
<?php
$uri = ltrim(urldecode(parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH)),'/');
if ($uri==null || !file_exists(__DIR__ . '/../' .$uri)) {
	$_GET['c'] = $uri;
	include_once '_index.php';
	return true;
}else{
	$_GET['c']='';
	return false;
}
```
Tell me if it's good for you.

**Comment by ekscrypto** [comment]
Seems to do the trick. Thanks!
