### ISSUE TITLE
[RFC] additional fields in select query

### ISSUE THREAD

**Issue by parsfanavar** [phpMv/ubiquity#83]
How can add additional field in select query which include its value to object properties (_rest)

`select table.*, concat(firstname," ",lastname) as fullname
`

**Comment by jcheron** [comment]
Thank you for this contribution.
I will have two reticences to make this change:
- Database and ORM operations are often more performance expensive than PHP code execution.
- I think it is better to keep an object or business approach.

Since ORM uses setters to assign values to object members, why not go through such a solution:
```php
class User {
    ...
	private function updateFullname(){
		$this->fullname = $this->firstname . ' ' . $this->lastname;
		$this->_rest['fullname'] = $this->fullname;
	}
	
	public function setFirstname($firstname) {
		$this->firstname = $firstname;
		$this->updateFullname();
	}

	public function setLastname($lastname) {
		$this->lastname = $lastname;
		$this->updateFullname();
	}
}
```

**Comment by parsfanavar** [comment]
What I mentioned in previous post  was a simple example query of what I meant. What a bout formula field, or `case when ... else ...` field, etc. In addition I think the above fields would be better calculated in database engine instead of foreach in php, isn't it?

**Comment by jcheron** [comment]
> I think the above fields would be better calculated in database engine instead of foreach in php, isn't it

If we compare the query to php processing, in a raw query context: yes
But the introduction of this feature requires additional processing at the ORM level:
- new mapping to be registered
- new processing to build the request

I'll do some tests (not right now I'm working on something else), and I'll keep you informed.

**Comment by UlasSAYGINIM** [comment]
@parsfanavar hi, i hope you are doing well.
can you give examples for your usage? 
i wonder it. I am new for ubiquity. trying to get what you want completely?

**Comment by jcheron** [comment]
@UlasSAYGINIM 
For me, the requirement consists in giving the possibility to add fields (calculated or not) to the SELECT part of the SQL query, and to associate this result to a member created at runtime of the loaded instances.

I think the **DAOPreparedQueries** should do that.
These are queries to prepare the ORM processing for future loading of instances, via `getById`, `getOne` or `getAll`, which is especially interesting with the **Swoole** or **Workerman** platforms.

Since these objects are stored, it is possible to add mapping information to them.


#### In practice
```php
DAO::prepareGetAll('users',\models\User::class);
DAO::getPrepared('users')->addMember('CONCAT(firstname," ",lastname)','fullname');
$users=DAO::executePrepared('users');//each user will have a fullname additional member
```
#### Concerned classes:
| Classes  | Role  |
|---|---|
| [DAOPreparedTrait](https://github.com/phpMv/ubiquity/blob/master/src/Ubiquity/orm/traits/DAOPreparedTrait.php)  | Defines the methods accessible from the DAO class.  |
| [DAOPreparedQuery](https://github.com/phpMv/ubiquity/blob/master/src/Ubiquity/orm/core/prepared/DAOPreparedQuery.php)  | PreparedQueries base class.  |
